### ISSUE TITLE
Service start failure

### ISSUE THREAD

**Issue by aminmazi** [hiddify/HiddifyNG#83]
loading core config
Preparing Domain: 
Prepare Result:
Domain: 
Port: 443
IPs: []
infra/conf/serial: failed to parse json config > infra/conf: failed to parse DNS config > infra/conf: failed to build nameserver > infra/conf: invalid domain rule: geosite:gfw-ir > infra/conf: failed to load geosite: GFW-IR > infra/conf: list not found in geosite.dat: GFW-IR
go.Universe$proxyerror: infra/conf/serial: failed to parse json config > infra/conf: failed to parse DNS config > infra/conf: failed to build nameserver > infra/conf: invalid domain rule: geosite:gfw-ir > infra/conf: failed to load geosite: GFW-IR > infra/conf: list not found in geosite.dat: GFW-IR
go.Universe$proxyerror: infra/conf/serial: failed to parse json config > infra/conf: failed to parse DNS config > infra/conf: failed to build nameserver > infra/conf: invalid domain rule: geosite:gfw-ir > infra/conf: failed to load geosite: GFW-IR > infra/conf: list not found in geosite.dat: GFW-IR
at libv2ray.V2RayPoint.runLoop(Native Method)
at com.v2ray.ang.service.V2RayServiceManager.startV2rayPoint(V2RayServiceManager.kt:155)
at com.v2ray.ang.service.V2RayVpnService$onStartCommand$1.invokeSuspend(V2RayVpnService.kt:362)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
{
"dns": {
"hosts": {
"domain:googleapis.cn": "googleapis.com"
},
"servers": [
"1.1.1.1",
{
"address": "1.1.1.1",
"domains": [
"geosite:gfw-ir"
],
"port": 53
}
]
},
"inbounds": [
{
"listen": "127.0.0.1",
"port": 10808,
"protocol": "socks",
"settings": {
"auth": "noauth",
"udp": true,
"userLevel": 8
},
"sniffing": {
"destOverride": [
"http",
"tls",
"quic"
],
"enabled": true
},
"tag": "socks"
},
{
"listen": "127.0.0.1",
"port": 10809,
"protocol": "http",
"settings": {
"userLevel": 8
},
"tag": "http"
},
{
"listen": "127.0.0.1",
"port": 10853,
"protocol": "dokodemo-door",
"settings": {
"address": "1.1.1.1",
"network": "tcp,udp",
"port": 53
},
"tag": "dns-in"
}
],
"log": {
"loglevel": "warning"
},
"outbounds": [
{
"mux": {
"concurrency": 8,
"enabled": false
},
"protocol": "vless",
"settings": {
"vnext": [
{
"address": "",
"port": 443,
"users": [
{
"encryption": "none",
"flow": "xtls-rprx-vision",
"id": "",
"level": 8,
"security": "auto"
}
]
}
]
},
"streamSettings": {
"network": "tcp",
"realitySettings": {
"allowInsecure": false,
"fingerprint": "chrome",
"publicKey": "",
"serverName": "",
"shortId": "6ba85144e30d4fc2",
"show": false,
"spiderX": ""
},
"security": "reality",
"sockopt": {
"dialer_proxy": "fragment_random"
},
"tcpSettings": {
"header": {
"type": "none"
}
}
},
"tag": "proxy"
},
{
"protocol": "freedom",
"settings": {},
"tag": "direct"
},
{
"protocol": "freedom",
"settings": {},
"streamSettings": {
"network": "tcp",
"security": "",
"sockopt": {}
},
"tag": "fragment"
},
{
"protocol": "freedom",
"settings": {},
"streamSettings": {
"network": "tcp",
"security": "",
"sockopt": {}
},
"tag": "fragment_random"
},
{
"protocol": "freedom",
"settings": {},
"streamSettings": {
"network": "tcp",
"security": "",
"sockopt": {}
},
"tag": "fragment_sni"
},
{
"protocol": "blackhole",
"settings": {
"response": {
"type": "http"
}
},
"tag": "block"
},
{
"protocol": "dns",
"tag": "dns-out"
}
],
"policy": {
"levels": {
"8": {
"connIdle": 300,
"downlinkOnly": 1,
"handshake": 4,
"uplinkOnly": 1
}
},
"system": {
"statsOutboundUplink": true,
"statsOutboundDownlink": true
}
},
"routing": {
"domainStrategy": "AsIs",
"rules": [
{
"inboundTag": [
"dns-in"
],
"outboundTag": "dns-out",
"type": "field"
},
{
"outboundTag": "proxy",
"port": "0-65535",
"type": "field"
}
]
},
"stats": {}
}

```

**Comment by Keivan-S** [comment]
--------- beginning of system
--------- beginning of crash
FATAL EXCEPTION: main
Process: ang.hiddify.com:RunSoLibV2RayDaemon, PID: 31212
android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{786427c u0 ang.hiddify.com/com.v2ray.ang.service.V2RayVpnService}
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2074)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:236)
at android.app.ActivityThread.main(ActivityThread.java:8037)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
2601): FATAL EXCEPTION: main
2601): Process: ang.hiddify.com:RunSoLibV2RayDaemon, PID: 2601
2601): android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{882f6a1 u0 ang.hiddify.com/com.v2ray.ang.service.V2RayVpnService}
2601): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2074)
2601): 	at android.os.Handler.dispatchMessage(Handler.java:106)
2601): 	at android.os.Looper.loop(Looper.java:236)
2601): 	at android.app.ActivityThread.main(ActivityThread.java:8037)
2601): 	at java.lang.reflect.Method.invoke(Native Method)
2601): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
2601): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
2968): FATAL EXCEPTION: main
2968): Process: ang.hiddify.com:RunSoLibV2RayDaemon, PID: 2968
2968): android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{9a3773d u0 ang.hiddify.com/com.v2ray.ang.service.V2RayVpnService}
2968): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2074)
2968): 	at android.os.Handler.dispatchMessage(Handler.java:106)
2968): 	at android.os.Looper.loop(Looper.java:236)
2968): 	at android.app.ActivityThread.main(ActivityThread.java:8037)
2968): 	at java.lang.reflect.Method.invoke(Native Method)
2968): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
2968): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
--------- beginning of main
loading core config
Preparing Domain: www.google.com:80
infra/conf/serial: failed to parse json config > infra/conf: empty selector list
go.Universe$proxyerror: infra/conf/serial: failed to parse json config > infra/conf: empty selector list
go.Universe$proxyerror: infra/conf/serial: failed to parse json config > infra/conf: empty selector list
at libv2ray.V2RayPoint.runLoop(Native Method)
at com.v2ray.ang.service.V2RayServiceManager.startV2rayPoint(V2RayServiceManager.kt:155)
at com.v2ray.ang.service.V2RayVpnService$onStartCommand$1.invokeSuspend(V2RayVpnService.kt:362)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
{
"dns": {
"hosts": {
"domain:googleapis.cn": "googleapis.com"
},
"servers": [
"1.1.1.1"
]
},
"inbounds": [
{
"listen": "127.0.0.1",
"port": 10808,
"protocol": "socks",
"settings": {
"auth": "noauth",
"udp": true,
"userLevel": 8
},
"sniffing": {
"destOverride": [
"http",
"tls",
"quic"
],
"enabled": true
},
"tag": "socks"
},
{
"listen": "127.0.0.1",
"port": 10809,
"protocol": "http",
"settings": {
"userLevel": 8
},
"tag": "http"
}
],
"log": {
"loglevel": "warning"
},
"outbounds": [],
"routing": {
"balancers": [
{
"selector": [],
"strategy": {
"settings": {
"accept_little_diff": true,
"count": 3,
"diff_percent": 0,
"interval": 600000,
"load_balancing": true,
"timeout": 10000,
"url": "https://cp.cloudflare.com"
},
"type": "optimal"
},
"tag": "balancer"
}
],
"domainStrategy": "AsIs",
"rules": [
{
"balancerTag": "balancer",
"outboundTag": "",
"port": "0-65535",
"type": "field"
}
]
}
}
Prepare Result:
Domain: www.google.com
Port: 80
IPs: [216.239.38.120]

**Comment by Keivan-S** [comment]
Same here
